resources:
- frontend/
- backend/
- database/
- ingress/

configMapGenerator:
- literals:
  - ASPNETCORE_ENVIRONMENT=Development
  name: common-config

images:
- name: myacrasestudent20.azurecr.io/capstone/express-server
  newTag: 0.0.2
- name: myacrasestudent20.azurecr.io/capstone/flask-api
  newTag: 0.0.2
- name: myacrasestudent20.azurecr.io/capstone/sqlite-db
  newTag: 0.0.2
- name: myacrasestudent20.azurecr.io/capstone/angular-app
  newTag: 0.0.2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
