resources:
- frontend/
- backend/
- database/
- ingress/

images:
- name: myacrasestudent20.azurecr.io/capstone/express-server
  newTag: 0.0.2
- name: myacrasestudent20.azurecr.io/capstone/flask-api
  newTag: 0.0.1
- name: nouchka/sqlite3
  newTag: latest
- name: myacrasestudent20.azurecr.io/capstone/angular-app
  newTag: 0.0.1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default