resources:
- frontend/
- backend/
- database/
- ingress/

images:
- name: myacrasestudent20.azurecr.io/capstone/express-server:0.0.1
  newTag: 0.0.2
- name: myacrasestudent20.azurecr.io/capstone/flask-api:0.0.1
  newTag: 0.0.2
- name: myacrasestudent20.azurecr.io/capstone/sqlite-db
  newTag: 0.0.2
- name: myacrasestudent20.azurecr.io/capstone/angular-app:0.0.1
  newTag: 0.0.2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default