apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlite-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlite-db
  template:
    metadata:
      labels:
        app: sqlite-db
    spec:
      containers:
      - name: sqlite-db
        image: myacrasestudent20.azurecr.io/capstone/sqlite-db
        volumeMounts:
        - name: sqlite-storage
          mountPath: /data
      volumes:
      - name: sqlite-storage
        emptyDir: {}